[project]
name = "mcp-servers"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "certifi>=2025.8.3",
    "dotenv>=0.9.9",
    "langchain-mcp-adapters>=0.1.9",
    "requests>=2.32.5",
    "truststore>=0.10.4",
]
